console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'right'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'unique'

  [[blocks.segments]]
    foreground = '#e91e63'
    type = 'status'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Working.Changed }}  <cyan>{{ .Working.String }}{{ end }}<cyan>{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}<magenta>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}<magenta>'
    foreground = 'grey'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = 'magenta'
    background = 'transparent'
    type = 'python'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ if and (gt .SHLVL 2) .Env.TMUX }}{{ .SHLVL }}{{ else if and (gt .SHLVL 1) (not .Env.TMUX) }}{{ .SHLVL }}{{ end }}'
    foreground = 'magenta'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    foreground = 'grey'
    type = 'time'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[tooltips]]
  foreground = 'yellow'
  background = 'transparent'
  type = 'kubectl'
  style = 'plain'
  tips = ['k', 'kubectl', 'helm', 'kubens', 'kubeseal', 'kubectx', 'oc', 'istioctl', 'kogito', 'kx', 'kns', 'k9s', 'telepresence', 'flux']

[[tooltips]]
  template = '{{if .Profile }}{{.Profile}}{{end}}{{if .Region}}@{{.Region}}{{end}}'
  foreground = 'yellow'
  background = 'transparent'
  type = 'aws'
  style = 'plain'
  tips = ['aws']

[[tooltips]]
  template = '{{ if .Version }}{{ .Version }}{{ end }}'
  foreground = 'yellow'
  background = 'transparent'
  type = 'terraform'
  style = 'plain'
  tips = ['terraform']

  [tooltips.properties]
    fetch_version = true

